theme: jekyll-theme-minimal
logo: /assets/img/photo_bill_circle.png
title: Johannes Bill
description: Postdoctoral researcher in computational neuroscience with Jan Drugowitsch and Sam Gershman

twitter_username: BillScientific
github_username:  billscientific
googlescholar_username: lWjexuQAAAAJ

